### SERVER
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

### SPRING
spring:
  application:
    name: voting-session-manager-service
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: ${MONGO_DB_URL:mongodb://root:toor@localhost:27017/admin}
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BROKER_URL:localhost:29092}

### APPLICATION
app:
  session:
    time: ${SESSION_TIME_SECONDS:60}
  kafka:
    topics:
      result-topic:
        name: ${RESULT_TOPIC_NAME:result-topic}

### LOGGING
logging:
  level:
    root: INFO
    com:
      example: TRACE

### SWAGGER
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method

### ACTUATOR
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
  info:
    env:
      enabled: true

### INFORMATION
info:
  app:
    name: "voting-session-manager-service"
    description: "Voting session manager service"
  author: "Edinei Goncalves"
  java-version: ${java.version}
